### PR TITLE
ignore dist folder

### PR DESCRIPTION
**Pull request by seunzone**
This PR helps to gitignore the `dist` folder.

### CODE REVIEW

**Comment by BolajiAyodeji** [comment]
We actually need the `dist` folder as the ES5 and minified ES5 versions are sourced from there.
The download link leads to the `dist` folder and ES6 version leads to `src`.

Do you have a better approach to this?

**Comment by seunzone** [comment]
I just figured you can close the PR.
But I'm thinking is there not a way to make this an npm package.
Then on the flip side, l remembered `axios`

**Comment by seunzone** [comment]
Good job bruv

**Comment by BolajiAyodeji** [comment]
> I just figured you can close the PR.
> But I'm thinking is there not a way to make this an npm package.
> Then on the flip side, l remembered `axios`

I was thinking of this too.
Since I have not created any npm package before, I'd use this to get started.
All these are just for learning and to make our development easier, `axios` started like this too :smile:

**Comment by BolajiAyodeji** [comment]
> Good job bruv

Thank you, Chief!
Did you check the AJAX one?

**Comment by BolajiAyodeji** [comment]
I'd publish the npm package for both next week :tada:

**Pull request closed without merging**
